config/routes.rb
Lifelog::Application.routes.draw do
  root 'home#index'
  get "home/index"

  get "time/categories"
  get "time/list"
  match "time/timelogs" => "time#timelogs", via: [:get, :post]
  match "time/categories" => "time#categories", via: [:get, :post]

  resources :clothes do
    collection {
      post :wear_today
    }
  end

  resources :healths
  resources :health_categories
  
  resources :categories do
    collection { 
      post :import 
    }
  end
  resources :timelogs do
    collection { 
      post :import 
      post :delete
      post :delete_multiple
    }
  end

  namespace :api do
    namespace :v2 do
      resources :timelogs
    end
  end

end

app/models/health.rb
class Health < ActiveRecord::Base
  def self.by_category(categoryName)
    dateStart = Health.order("logged_at").first.logged_at
    dateEnd = Health.order("logged_at").last.logged_at

    # create a hash for each date
    cat = (dateStart.to_date..dateEnd.to_date).each_with_object({}) do |date,hash|
    hash[date] = 0
    end

    # cat = Hash.new { |h,k| h[k] = 0}  
    
    catid = HealthCategory.find_by(name: categoryName).id
    Health.where(health_category_id: catid).each do |health|
      cat[health.logged_at.to_date] = health.value
    end
    cat
  end
end

app/controllers/healths_controller.rb
class HealthsController < ApplicationController
  def index
    @healths = Health.all
    respond_to do |format|
      format.html
      format.csv { send_data @healths.to_csv}
    end
  end
  def new
    @health = Health.new
  end
  def create
    @health = Health.new(health_params)
    if @health.save
      redirect_to @health
    else
      render 'new'
    end
  end

  private
  def health_params
    params.require(:health).permit(:logged_at, :value, :health_category_id, :notes)
  end

end

app/helpers/healths_helper.rb
module HealthsHelper
end

app/views/healths/_form.html.erb
<%= form_for @health do |f| %>
  <% if @health.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@health.errors.count, "error") %>:</h2>
      <ul>
	<% @health.errors.full_messages.each do |msg| %>
	  <li><%= msg %></li>
	<% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :time %>
    <%= f.datetime_select :logged_at %>
  </p>
  <p>
    <%= f.label :value %>
    <%= f.text_field :value %>
  </p>
  <p>
    <%= f.label :notes %>
    <%= f.text_field :notes %>
  </p>
  <p>
    <%= f.label :category %>
    <%= f.select :health_category_id, options_for_select(HealthCategory.all.collect{|c|[c.name, c.id]}.insert(0,"none")) %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/healths/index.html.erb
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

<h1>Healths</h1>

<p><%= link_to 'New health log', new_health_path %></p>

<% poo = Health.by_category("poo") %>
<%= line_chart [
    {name: "weight", data: Health.by_category("weight")},
    {name: "poo", data: poo.each{|k,v| poo[k] = 55+v*5} }
    ],min:55, max:60, library: { hAxis: {format:'MMM dd'}, curveType: 'none'} 
    %>

<%= %>

<% @healths.each do |health| %>  
  <%= health.logged_at %> <%= HealthCategory.find_by_id(health.health_category_id).name %> <%= health.value %> <%= HealthCategory.find_by_id(health.health_category_id).unit %> <%= health.notes %> 
  <%= link_to 'Show', health_path(health) %> 
  <%= link_to 'Edit', edit_health_path(health) %> 
  <%= link_to 'Delete', health_path(health), method: :delete, data: { confirm: 'Are you sure?' } %>
</br>
<% end %>

app/views/healths/new.html.erb
<h1>Health: new</h1>

<%= render 'form' %>

<%= link_to 'Back', healths_path %>