config/routes.rb
Lifelog::Application.routes.draw do
  root 'home#index'
  get "home/index"

  get "time/categories"
  get "time/list"
  match "time/timelogs" => "time#timelogs", via: [:get, :post]
  match "time/categories" => "time#categories", via: [:get, :post]

  resources :clothes do
    collection {
      post :wear_today
    }
  end

  resources :healths
  resources :health_categories
  
  resources :categories do
    collection { 
      post :import 
    }
  end
  resources :timelogs do
    collection { 
      post :import 
      post :delete
      post :delete_multiple
    }
  end

  namespace :api do
    namespace :v2 do
      resources :timelogs
    end
  end

end

app/models/clothe.rb
class Clothe < ActiveRecord::Base
  serialize :wear, Array
  validates :name, presence: true, uniqueness: {message: "should have unique name"}
  
  # Getter
  def worn
    Date.today.strftime("%d %b %Y")
  end

  # Setter
  def worn=(date)    
    wear << date
  end

  def lastWorn
    wear.sort_by{|date| DateTime.parse(date)}.last
  end
  
  def times
    wear.size
  end

  def self.getPerDay
    # get clothes id per day recorded
    clothesPerDay= Hash.new { |h,k| h[k] = [] }
    Clothe.all.each do |clothe|
      clothe.wear.sort_by{|date| DateTime.parse(date)}.each do |date|
        clothesPerDay[date] << clothe.id
      end
    end
    clothesPerDay
  end
  
end

app/controllers/clothes_controller.rb
class ClothesController < ApplicationController
  helper_method :sort_column, :sort_direction
  
  def index
    if sort_column == "times"
      @clothes = Clothe.all.sort_by{|c| c.times}
    else
      if sort_column == "lastWorn"
        @clothes = Clothe.all.sort_by{|c| DateTime.parse(c.lastWorn)}        
      else 
        @clothes = Clothe.order(sort_column + ' asc').all
      end
    end
    if sort_direction == "desc"
      @clothes.reverse!
    end
    @clothesPerDay = Clothe.getPerDay
  end
  
  def new
    @clothe = Clothe.new
  end

  def show
    @clothe = Clothe.find(params[:id])
  end
  
  def create
    @clothe = Clothe.new(clothe_params)
    if @clothe.save
      redirect_to action: "index"
    else
      render :new
    end
  end
  def edit
    @clothe = Clothe.find(params[:id])
  end

  def update
    @clothe = Clothe.find(params[:id])
    if @clothe.update(clothe_params)
      redirect_to action: "index"
    else
      render 'edit'
    end
  end

  def wear_today
    @clothe = Clothe.find(params[:format])
    @clothe.wear << Date.today.strftime("%d %b %Y")
    @clothe.save
    flash[:notice] = "#{@clothe.name} is worn today."
    redirect_to clothes_path
  end
  
  private
  def clothe_params
    params.require(:clothe).permit(:name, :brand, :bought, :worn) 
  end

  # default sorting value
  def sort_column
    params[:sort] || "name"
  end
  
  def sort_direction
    params[:direction] || "asc"
  end
end

app/helpers/clothes_helper.rb
module ClothesHelper
end

app/views/clothes/_clothe.html.erb
<tr>
  <td><%= clothe.id %></td>
  <td><%= clothe.brand %></td>
  <td><%= link_to clothe.name, edit_clothe_path(clothe) %></td>
  <td><%= clothe.wear.size %></td>
  
  <td>
    <% if(clothe.wear.size > 0) %>
    <%= clothe.lastWorn %>
    <% end %>    
  </td>
  <td><%= clothe.bought %></td>
  <td><%= link_to "today",  wear_today_clothes_path(clothe), method: :post  %></td>
</tr>

app/views/clothes/_form.html.erb
<% if @clothe.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@clothe.errors.count, "error") %>:</h2>
  <ul>
    <% @clothe.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form_for @clothe  do |f| %>
<p>
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</p>

<p>
  <%= f.label :brand %><br>
  <%= f.text_field :brand %>
</p>

<p>
  <%= f.label :bought %>
  <%= f.datetime_select :bought %>
</p>

<p>
  <%= f.label :worn %>
  <%= f.text_field :worn %>
  <br />
  <%= @clothe.wear %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>

app/views/clothes/edit.html.erb
<h1>Clothes: edit</h1>

<%= render 'form' %>

<%= link_to 'Back', clothes_path %>

app/views/clothes/index.html.erb
<% if flash[:notice] %>
<div class="notice"><%= flash[:notice] %></div>
<% end %>

<h1>Clothes</h1>

<%= link_to 'New clothes', new_clothe_path %> <%= link_to 'Home', root_path %>

<h2>Today</h2>
<table>
<% @clothes.each do |clothe| %>
<%if clothe.wear.sort_by{|date| DateTime.parse(date)}.last == Date.today.strftime("%d %b %Y") %>
<%= render clothe %>
<% end %>
<% end %>
</table>

<h2>List</h2>
<p>Number of clothes <%= Clothe.count %></p>

<table>
  <tr>
    <th><%= sortable "id" %></th>
    <th><%= sortable "brand" %></th>
    <th><%= sortable "name" %></th>
    <th><%= sortable "times" %></th>
    <th><%= sortable "lastWorn", "last worn" %></th>
    <th><%= sortable "bought" %></th>
    <th>today</th>
  </tr>

  <% @clothes.each do |clothe| %>
  <%= render clothe %>
  <% end %>
</table>

<h2>Per Day</h2>
<table>
  <% @clothesPerDay.sort_by{|date,ids| DateTime.parse(date)}.reverse_each do |date,ids| %>
  <tr>
    <td><%= date %></td>
    <td>
      <% ids.each do |id| %>
      <% clothe = Clothe.find_by_id(id) %>
      <%= link_to clothe.name, edit_clothe_path(clothe) %><br />
      <% end %>
    </td>
  </tr>
<% end %>
</table>

app/views/clothes/new.html.erb
<h1>Clothes: new</h1>

<%= render 'form' %>

<%= link_to 'Back', clothes_path %>