config/routes.rb
Lifelog::Application.routes.draw do
  root 'home#index'
  get "home/index"

  get "time/categories"
  get "time/list"
  match "time/timelogs" => "time#timelogs", via: [:get, :post]
  match "time/categories" => "time#categories", via: [:get, :post]

  resources :clothes do
    collection {
      post :wear_today
    }
  end

  resources :healths
  resources :health_categories
  
  resources :categories do
    collection { 
      post :import 
    }
  end
  resources :timelogs do
    collection { 
      post :import 
      post :delete
      post :delete_multiple
    }
  end

  namespace :api do
    namespace :v2 do
      resources :timelogs
    end
  end

end

app/models/health_category.rb
class HealthCategory < ActiveRecord::Base
end

app/controllers/health_categories_controller.rb
class HealthCategoriesController < ApplicationController
  def index
    @health_categories = HealthCategory.all    
    respond_to do |format|
      format.html
      format.csv { send_data @health_categories.to_csv}
    end
  end
  def new
    @health_category = HealthCategory.new
  end
  def create
    @health_category = HealthCategory.new(health_category_params)
    if @health_category.save
      redirect_to @health_category
    else
      render 'new'
    end
  end

  private
  def health_category_params
    params.require(:health_category).permit(:name, :unit)
  end

end

app/helpers/health_categories_helper.rb
module HealthCategoriesHelper
end

app/views/health_categories/_form.html.erb
<%= form_for @health_category do |f| %>
  <% if @health_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@health_category.errors.count, "error") %>:</h2>
      <ul>
	<% @health_category.errors.full_messages.each do |msg| %>
	  <li><%= msg %></li>
	<% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :unit %>
    <%= f.text_field :unit %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/health_categories/index.html.erb
<h1>Health Categories</h1>

<p><%= link_to 'New health category', new_health_category_path %></p>

<% @health_categories.each do |health_category| %>  
  <%= health_category.id %>   <%= health_category.name %>   <%= health_category.unit %> 
  <%= link_to 'Show', health_category_path(health_category) %> 
  <%= link_to 'Edit', edit_health_category_path(health_category) %> 
  <%= link_to 'Delete', health_category_path(health_category), method: :delete, data: { confirm: 'Are you sure?' } %>
</br>
<% end %>

app/views/health_categories/new.html.erb
<h1>Health Category: new</h1>

<%= render 'form' %>

<%= link_to 'Back', health_categories_path %>