config/routes.rb
Lifelog::Application.routes.draw do
  root 'home#index'
  get "home/index"

  get "time/categories"
  get "time/list"
  match "time/timelogs" => "time#timelogs", via: [:get, :post]
  match "time/categories" => "time#categories", via: [:get, :post]

  resources :clothes do
    collection {
      post :wear_today
    }
  end

  resources :healths
  resources :health_categories
  
  resources :categories do
    collection { 
      post :import 
    }
  end
  resources :timelogs do
    collection { 
      post :import 
      post :delete
      post :delete_multiple
    }
  end

  namespace :api do
    namespace :v2 do
      resources :timelogs
    end
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :timelogs
  validates :name, uniqueness: true, format: {without: /\s/}, presence: true
  validates :shortcut, format: {without: /\s/}
  validates_uniqueness_of :shortcut, allow_blank: true
  belongs_to :parent, class_name: 'Category'

  acts_as_tree_with_dotted_ids

  before_save do
    self.name = self.name.downcase
    if !self.shortcut.blank?
      self.shortcut = self.shortcut.downcase
    end
  end

  def self.to_csv(options = {}) 
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |category|
        csv << category.attributes.values_at(*column_names)
      end
    end
  end
  
  #import csv
  def self.import(file)    
    CSV.foreach(file.path, headers: true) do |row|      
      row_hash = row.to_hash
      id = ""
      if row_hash["parent"]        
        if Category.find_by_shortcut(row_hash["parent"].downcase)
          id = Category.find_by_shortcut(row_hash["parent"].downcase).id
        else 
          if Category.find_by_name(row_hash["parent"].downcase)
            id = Category.find_by_name(row_hash["parent"].downcase).id
          end
        end
        if id.blank?
          raise "parent #{row_hash["parent"]} name #{row_hash["name"]}"
        end
      end
      category = Category.new(name: row_hash["name"], shortcut: row_hash["shortcut"], notes: row_hash["notes"], color: row_hash["color"], parent_id: id)
      if category.save
      else
        raise "error on #{category.name} #{category.shortcut}"
      end
    end                
  end
   
  def self.parentNameToNote 
    all.each do |category|
      unless category.parent_id.nil?        
        category.notes = Category.find_by_id(category.parent_id).name
        category.save
      end
    end
  end
    
  def self.fix0parentId
    all.each do |category|
      if category.parent_id == 0
        category.parent_id = nil
        category.save
      end    
    end
  end
      
  def self.secondsToString(t)
    mm, ss = t.divmod(60)   
    hh, mm = mm.divmod(60)  
    dd, hh = hh.divmod(24)
    if dd > 0
      return "%d days %02d:%02d" % [dd,hh,mm]
    else
      return "%02d:%02d" % [hh,mm]
    end
  end

  def sum_up(options)
    summed = Hash.new { |h,k| h[k] = 0}  
    summed[:name] = self_and_ancestors.reverse.map{ |c| c.name }.join(' - ').html_safe    
    unless all_children.empty?
      catid = all_children.map{|i| i[:id]}.push(id)
    else
      catid = id
    end
    summed[:cat] = catid
    summed[:color] = root.color
    logs = Timelog.where(time: options[:begin]..options[:end]).order("time desc").where("category_id IN (?)",catid)
    summed[:logs] = logs
    if logs
      seconds = logs.pluck(:duration).sum
      summed[:duration] = seconds
    end
    summed
  end

  #time view, sumarize by root category
  def self.summarize(options)
    summary = Hash.new { |h,k| h[k] = Hash.new { |h2,k2| } }

    Category.where(parent_id: [nil,0]).each do |category|
      summary[:category][category.id] = 0
      summary[:timelog][category.id] = []
    end

    summary[:range][:begin] = options[:begin]
    summary[:range][:end] = options[:end]
     
    summary[:excess][:prev] = Timelog.where("time < ?",options[:begin]).order("time desc").first

    timelogRange = Timelog.where("time >= ? AND time <= ? AND duration > 0", options[:begin],options[:end]).order("time")
    
    timelogRange.each do |timelog|
      category = Category.find_by_id(timelog.category_id)
      summary[:category][category.root.id] += timelog.duration
      summary[:timelog][category.root.id] << timelog
    end

    #plus first timelog's excess duration
    summary[:category][Category.find_by_id(summary[:excess][:prev].category_id).root.id] += timelogRange.first.time-summary[:range][:begin].midnight
    summary[:timelog][Category.find_by_id(summary[:excess][:prev].category_id).root.id] << summary[:excess][:prev]
    
    #minus last timelog's excess duration
    summary[:category][Category.find_by_id(timelogRange.last.category_id).root.id] -= timelogRange.last.duration
    endtime = summary[:range][:end]
    if(Time.zone.now < endtime)
      endtime = Time.zone.now
    end
    summary[:category][Category.find_by_id(timelogRange.last.category_id).root.id] += endtime-timelogRange.last.time+60

    summary[:total][:category] = 0
    summary[:category].each do |category,duration|
      summary[:plot][Category.find_by_id(category).name] = duration/3600.0
      summary[:total][:category] += duration
    end

    summary[:colors] = Array.new
    summary[:category].each do |cat| 
      summary[:colors].push Category.find_by_id(cat).root.color 
    end 

    summary

  end
  
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all    
    respond_to do |format|
      format.html
      format.csv { send_data @categories.to_csv}
    end
  end
  def new
    @category = Category.new
  end
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to @category
    else
      render 'new'
    end
  end
  def show
    @category = Category.find(params[:id])
    @timelogs = Timelog.where(category_id: params[:id])
  end
  def edit
    @category = Category.find(params[:id])
  end
  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to @category
    else
      render 'edit'
    end
  end
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end
  def import
    Category.import(params[:file])
    redirect_to categories_path, notice: "Categories imported."
  end

  private
  def category_params
    params.require(:category).permit(:name, :notes, :shortcut, :color, :parent_id, :category_id)
  end

end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %>:</h2>
      <ul>
	<% @category.errors.full_messages.each do |msg| %>
	  <li><%= msg %></li>
	<% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :shortcut %>
    <%= f.text_field :shortcut %>
  </p>
  <p>
    <%= f.label :color %>
    <%= f.text_field :color %>
  </p>
  <p>
    <%= f.label :notes %>
    <%= f.text_field :notes %>
  </p>
  <p>
    <%= f.label :parent %>
    <%= f.select :parent_id, options_for_select(Category.all.collect{|c|[c.name, c.id]}.insert(0,"none")) %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/categories/edit.html.erb
<h1>Categories: edit</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<p>
<%= link_to 'New category', new_category_path %>
<%= link_to 'Home', root_path %>
<%= link_to "csv", categories_path(format: "csv") %>
</p>

<% @categories.each do |category| %>
  
  <span style="display: inline; background-color: <%= category.color %>;">
  <%= category.name %> <%= category.shortcut %> <%= category.notes %> 
  </span>
  <%= link_to 'Show', category_path(category) %> 
  <%= link_to 'Edit', edit_category_path(category) %> 
  <%= link_to 'Delete', category_path(category), method: :delete, data: { confirm: 'Are you sure?' } %>
</br>
<% end %>

<h2>Import CSV</h2>
<%= form_tag import_categories_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>

app/views/categories/new.html.erb
<h1>Category: new</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
 
<p>
  <strong>Shortcut:</strong>
  <%= @category.shortcut %>
</p>

<p>
  <strong>Color:</strong>
  <span style="display: inline; background-color: <%= @category.color %>; padding: 5px;"><%= @category.color %></span>
</p>

<p>
  <strong>Notes:</strong>
  <%= @category.notes %>
</p>


<% if @category.parent_id %>
  <% parent = Category.find_by_id(@category.parent_id) %>
  <% if parent %>
    <p>
      <strong>Parent:</strong>
      <%= link_to parent.name, category_path(parent)  %>
    </p>
  <% end %>
<% end %>

<h2>Timelogs:</h2>
<%= render @category.timelogs %>

<% if @category.id == 1 %>
<h2>Blank categories:</h2>
<% Timelog.all.each do |timelog| -%>
  <%= render timelog  %>
<% end -%>
<% end %>

<%= link_to 'Back', categories_path %>
| <%= link_to 'Edit', edit_category_path(@category) %>